name: Generated Files

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  gomod:
    name: Go Modules
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.20'

    - name: Go caches
      uses: actions/cache@v2
      with:
        path: |
          ~/go/pkg/mod
        key: ${{ github.job }}-${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ github.job }}-${{ runner.os }}-go-

    - name: Check modules requirements
      run: |
        go mod tidy

        git_status="$(git status --porcelain)"
        if [[ ${git_status} ]]; then
            echo -e 'Go modules are out-of-date. Please run `go mod tidy`\n'
            echo "${git_status}"
            exit 1
        fi
